# Generated by Django 4.1.2 on 2023-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTesting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'application_testing',
                'managed': False,
            },
        ),
    ]
