# Generated by Django 4.1.2 on 2023-01-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='city',
            field=models.CharField(max_length=199),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(max_length=199),
        ),
    ]
