# Generated by Django 4.1.2 on 2023-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_city_gateway_gateway_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gateway_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=199)),
                ('servername', models.TextField(max_length=199)),
                ('gateway_name', models.TextField(max_length=199)),
                ('org_id', models.TextField(max_length=199)),
                ('latitude', models.TextField(max_length=199)),
                ('longitude', models.TextField(max_length=199)),
                ('loc_name', models.TextField(max_length=199)),
                ('loc_region', models.TextField(max_length=199)),
            ],
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='gateway_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='servername',
            new_name='name',
        ),
    ]
